"use client";
import {ArrowUpRight,ArrowDown,Download,Sun,Moon,MapPin} from 'lucide-react';
import {useEffect,useState} from 'react';
import PortfolioContent,{MobileMenu,SocialIcon} from './portfolio-content';
import KineticScene from './kinetic-scene';
export default function Home(){
 const [dark,setDark]=useState(false);
 useEffect(()=>{try{setDark(localStorage.getItem('shehab-theme')==='dark')}catch{}},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches||!matchMedia('(pointer: fine)').matches)return;
  const targets=document.querySelectorAll<HTMLElement>('.project-visual,.skill-card,.identity-card');
  const move=(e:PointerEvent)=>{const el=e.currentTarget as HTMLElement,r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;el.style.setProperty('--tilt-x',`${(y-.5)*-5}deg`);el.style.setProperty('--tilt-y',`${(x-.5)*6}deg`);el.style.setProperty('--spot-x',`${x*100}%`);el.style.setProperty('--spot-y',`${y*100}%`)};
  const leave=(e:PointerEvent)=>{const el=e.currentTarget as HTMLElement;el.style.setProperty('--tilt-x','0deg');el.style.setProperty('--tilt-y','0deg')};
  targets.forEach(el=>{el.addEventListener('pointermove',move);el.addEventListener('pointerleave',leave)});return()=>targets.forEach(el=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave)})
 },[]);
 return <><a className="skip-link" href="#main">Skip to content</a>
 <header className="site-header"><a href="#home" className="brand brand-symbol" aria-label="Shehab Abedrabuh home"><svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M45 14H24L13 25l27 14-11 11H8" stroke="currentColor" strokeWidth="7" strokeLinejoin="round"/><path d="m35 50 13-32 12 32M41 38h14" stroke="var(--purple)" strokeWidth="6" strokeLinejoin="round"/></svg></a><nav aria-label="Main navigation">{['Home','About','Experience','Skills','Projects','Services','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}<a href="https://buymeacoffee.com/shehab.bio" target="_blank" rel="noopener noreferrer" className="nav-support">Support</a></nav><div className="header-actions"><a className="cv-link" href="/Shehab-Abedrabuh-CV.pdf" download>Download CV <Download size={15}/></a><button className="icon-button" aria-label={dark?'Switch to light mode':'Switch to dark mode'} onClick={()=>{setDark(!dark);try{localStorage.setItem('shehab-theme',dark?'light':'dark')}catch{}}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><MobileMenu/></div></header>
 <main id="main"><section className="hero hero-kinetic" id="home"><div className="aurora" aria-hidden="true"/><div className="hero-topline container"><span><MapPin size={12}/> NABLUS, PALESTINE</span><span>A PERSONAL PORTFOLIO</span></div><div className="hero-grid container"><div className="hero-copy"><div className="availability"><span/>Available for full-time, part-time & freelance</div><p className="eyebrow intro">SHEHAB ABEDRABUH</p><h1 className="animated-headline"><span className="headline-mask"><span>My work.</span></span><span className="headline-mask"><span>My <em>progress.</em></span></span><span className="heading-period" aria-hidden="true">✳</span></h1><p className="hero-role"><span>Technical Support Specialist</span><i aria-hidden="true"> / </i><span>Systems & Infrastructure</span><i aria-hidden="true"> / </i><span>Junior DevOps</span></p><p className="hero-description">I turn technical problems into clear solutions.<br className="desktop-break"/> Helping people work better, with technology they can rely on.</p><div className="hero-buttons"><a className="button primary" href="#projects"><span>Explore my work</span><span className="button-arrow"><ArrowUpRight size={20}/></span></a><a className="button secondary" href="#services">How I can help <ArrowUpRight size={18}/></a></div><div className="hero-links"><a href="#contact">Let’s talk <ArrowUpRight size={15}/></a><span/><a href="https://www.linkedin.com/in/shehababedrabuh" target="_blank" rel="noreferrer" aria-label="LinkedIn"><SocialIcon type="linkedin"/></a><a href="https://github.com/shehab-abedrabuh" target="_blank" rel="noreferrer" aria-label="GitHub"><SocialIcon type="github"/></a></div></div><KineticScene/></div><div className="hero-bottom container"><span><b>01 — 07</b> SCROLL TO EXPLORE</span><a href="#about"><span>From solving problems<br/>to building possibilities.</span><span className="scroll-circle"><ArrowDown size={20}/></span></a></div></section><div className="discipline-strip" aria-label="Technical support, systems and infrastructure"><div><span>Technical support</span><i>✳</i><span>Systems & infrastructure</span><i>✳</i><span>Junior DevOps</span><i>✳</i></div></div><PortfolioContent/></main></>;
}
